### ISSUE TITLE
CoreFoundation 和 CoreServices 找不到

### ISSUE THREAD

**Issue by CCint3** [zgr0629/RedisDesktopManager-Mac#5]
```
clang: error: no such file or directory: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'
clang: error: no such file or directory: '/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices'
```
这个错误怎么处理呢。

**Comment by zgr0629** [comment]
> ```
> 
> clang: error: no such file or directory: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'
> 
> clang: error: no such file or directory: '/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices'
> 
> ```
> 
> 这个错误怎么处理呢。
> 
> 

big sur 编译的问题，见主页readme底部说明，现在用github action编译了。

**Comment by CCint3** [comment]
> > ```
> > 
> > clang: error: no such file or directory: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'
> > 
> > clang: error: no such file or directory: '/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices'
> > ```
> > 
> > 
> > 这个错误怎么处理呢。
> 
> big sur 编译的问题，见主页readme底部说明，现在用github action编译了。

下载你编译好的dmg后不能运行。
![image](https://user-images.githubusercontent.com/31920574/100104913-b8349c00-2ea1-11eb-9f59-7a0942d1acf2.png)

**Comment by zgr0629** [comment]
我试了一下，我这边几台升级了big sur的电脑都是可以打开的
看看你的电脑设置，安全隐私，是不是没有设置“允许任何来源”？
如果是的话参考一下这个搜索结果，设置一下再试试看
https://www.google.com/search?q=mac+software+anywhere
