### ISSUE TITLE
2020.6版的启动不了

### ISSUE THREAD

**Issue by Sxxjava** [zgr0629/RedisDesktopManager-Mac#6]
如题, 是我这边需要执行brew install python@3.7安装一下python3.7吗?
dyld: Library not loaded: /usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users/sincere/Desktop/RDM.app/Contents/MacOS/RDM
  Reason: image not found
[1]    2874 abort      /Users/sincere/Desktop/

**Comment by zgr0629** [comment]
是的

**Comment by Sxxjava** [comment]
好的,谢谢!
